### ISSUE TITLE
win11操作系统运行apps里面的agentfabric应用，当配置(Configure)时勾选“内置能力”：Code Interpreter，点击更新配置会报错

### ISSUE THREAD

**Issue by yangandiris** [modelscope/modelscope-agent#244]
代码是master分支最新版本，同样的操作在mac系统上时没有报错，如下是错误详情：

C:\Users\Administrator\AppData\Local\Programs\Python\Python311\python.exe D:\Models\modelscope-agent\apps\agentfabric\app.py 
2024-01-02 15:22:03,487 - modelscope - INFO - PyTorch version 2.1.1+cu121 Found.
2024-01-02 15:22:03,488 - modelscope - INFO - Loading ast index from D:\Models\modelscope\ast_indexer
2024-01-02 15:22:03,737 - modelscope - INFO - No valid ast index found from D:\Models\modelscope\ast_indexer, generating ast index from prebuilt!
2024-01-02 15:22:03,786 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 1e9c69939b0ce4064535823b88c0fb8a and a total number of 946 components indexed
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2024-01-02 15:22:13.093 - modelscope-agent - INFO -  | message: builder_cfg | uuid: local_user | request_id: default_request_id | content: {'builder_cfg': "Config (path: D:/Models/modelscope-agent/agentfabric\\config\\builder_config.json): {'name': '', 'avatar': 'image.png', 'description': '', 'instruction': '', 'prompt_recommend': ['你可以做什么？', '你有什么功能？', '如何使用你的功能？', '能否给我一些示例指令？'], 'knowledge': [], 'tools': {'image_gen': {'name': 'Wanx Image Generation', 'is_active': True, 'use': True, 'is_remote_tool': True}, 'code_interpreter': {'name': 'Code Interpreter', 'is_active': True, 'use': True, 'is_remote_tool': False, 'max_output': 2000}, 'web_browser': {'name': 'Web Browsing', 'is_active': True, 'use': False, 'max_browser_length': 2000}, 'amap_weather': {'name': '高德天气', 'is_active': True, 'use': False}, 'wordart_texture_generation': {'name': '艺术字纹理生成', 'is_active': True, 'use': False}, 'web_search': {'name': 'Web Searching', 'is_active': True, 'use': False, 'searcher': 'bing'}, 'qwen_vl': {'name': 'Qwen-VL识图', 'is_active': True, 'use': True}, 'style_repaint': {'name': '人物风格重绘', 'is_active': True, 'use': False}, 'modelscope_text-address': {'name': '地址解析', 'url': 'https://api-inference.modelscope.cn/api-inference/v1/models/damo/mgeo_geographic_elements_tagging_chinese_base', 'use': False, 'is_active': True, 'is_remote_tool': True}, 'modelscope_text-ner': {'name': '命名实体识别', 'url': 'https://api-inference.modelscope.cn/api-inference/v1/models/damo/nlp_raner_named-entity-recognition_chinese-base-cmeee', 'use': False, 'is_active': True, 'is_remote_tool': True}, 'modelscope_video-generation': {'name': '视频生成', 'url': 'https://api-inference.modelscope.cn/api-inference/v1/models/damo/text-to-video-synthesis', 'use': False, 'is_active': True, 'is_remote_tool': True}}, 'model': 'qwen-max', 'language': 'zh'}"} | step:  | error: 
2024-01-02 15:22:13.187 - modelscope-agent - INFO -  | message: using model qwen-max | uuid: local_user | request_id: default_request_id | content: {'model_config': {'type': 'dashscope', 'model': 'qwen-max', 'length_constraint': {'knowledge': 4000, 'input': 6000}, 'generate_cfg': {'use_raw_prompt': True, 'top_p': 0.5, 'stop': 'Observation'}}} | step:  | error: 
2024-01-02 15:22:14,427 - modelscope - WARNING - Model revision not specified, use revision: v1.1.0
2024-01-02 15:22:14,648 - modelscope - INFO - initiate model from D:\Models\modelscope\damo\nlp_gte_sentence-embedding_chinese-base
2024-01-02 15:22:14,648 - modelscope - INFO - initiate model from location D:\Models\modelscope\damo\nlp_gte_sentence-embedding_chinese-base.
2024-01-02 15:22:14,649 - modelscope - INFO - initialize model from D:\Models\modelscope\damo\nlp_gte_sentence-embedding_chinese-base
2024-01-02 15:22:15,566 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-02 15:22:15,567 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-02 15:22:15,567 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\Models\\modelscope\\damo\\nlp_gte_sentence-embedding_chinese-base'}. trying to build by task and model information.
2024-01-02 15:22:15,597 - modelscope - WARNING - No preprocessor field found in cfg.
2024-01-02 15:22:15,597 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-02 15:22:15,597 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'D:\\Models\\modelscope\\damo\\nlp_gte_sentence-embedding_chinese-base', 'sequence_length': 128}. trying to build by task and model information.
2024-01-02 15:22:15.616 - modelscope-agent - INFO -  | message: Initiating prompt generator. | uuid: default_user | request_id: default_request_id | content: {'agent_type': <AgentType.MRKL: 'mrkl'>, 'model': '<modelscope_agent.llm.dashscope_llm.DashScopeLLM object at 0x0000020A47B51E90>', 'kwargs': "{'prompt_generator': 'ZhCustomPromptGenerator', 'add_addition_round': True, 'knowledge_file_name': '', 'uuid_str': 'local_user'}"} | step:  | error: 
2024-01-02 15:22:15.617 - modelscope-agent - INFO -  | message: Initiating action parser. | uuid: default_user | request_id: default_request_id | content: {'agent_type': <AgentType.MRKL: 'mrkl'>, 'model': '<modelscope_agent.llm.dashscope_llm.DashScopeLLM object at 0x0000020A47B51E90>', 'kwargs': "{'action_parser': None, 'add_addition_round': True, 'knowledge_file_name': '', 'uuid_str': 'local_user'}"} | step:  | error: 
INFO: kernel process's PID = 16316
Traceback (most recent call last):
  File "D:\tmp\ci_workspace\launch_kernel_14324.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\__init__.py", line 5, in <module>
    from .connect import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\connect.py", line 12, in <module>
    import jupyter_client
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_client\channels.py", line 4, in <module>
    import asyncio
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\__init__.py", line 42, in <module>
    from .windows_events import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 8, in <module>
    import _overlapped
OSError: [WinError 10106] �޷����ػ��ʼ������ķ����ṩ����

**Comment by slin000111** [comment]
可能有些依赖目前还不支持windows，linux系统上可以。

**Comment by zzhangpurdue** [comment]
目前的code interpreter需要在linux/mac上进行，暂时不支持windows
