### ISSUE TITLE
Bug解答：点击构建按钮报错？

### ISSUE THREAD

**Issue by yinjianjie** [modelscope/modelscope-agent#255]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1192, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/modelscope-agent/apps/agentfabric/app.py", line 615, in publish_agent
    output_url, envs_required = prepare_agent_zip(name, DEFAULT_AGENT_DIR,
  File "/mnt/workspace/modelscope-agent/apps/agentfabric/publish_util.py", line 87, in prepare_agent_zip
    auth = oss2.Auth(ak_id, ak_secret)
  File "/opt/conda/lib/python3.10/site-packages/oss2/auth.py", line 221, in __init__
    credentials_provider = StaticCredentialsProvider(access_key_id.strip(), access_key_secret.strip())
AttributeError: 'NoneType' object has no attribute 'strip'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1192, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/lib/python3.10/site-packages/gradio/utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/modelscope-agent/apps/agentfabric/app.py", line 615, in publish_agent
    output_url, envs_required = prepare_agent_zip(name, DEFAULT_AGENT_DIR,
  File "/mnt/workspace/modelscope-agent/apps/agentfabric/publish_util.py", line 87, in prepare_agent_zip
    auth = oss2.Auth(ak_id, ak_secret)
  File "/opt/conda/lib/python3.10/site-packages/oss2/auth.py", line 221, in __init__
    credentials_provider = StaticCredentialsProvider(access_key_id.strip(), access_key_secret.strip())
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by zzclynn** [comment]
本地使用的话，需要你提供oss的配置，因为是使用oss，如果是创空间里面用这个出错，那可能是因为在更新？

**Comment by yinjianjie** [comment]
请问是在哪个文件里配置oss未来可期------------------ 原始邮件 ------------------发件人: Zhicheng Zhang  ***@***.***>发送时间: 2024年1月11日 15:22收件人: modelscope/modelscope-agent ***@***.***>抄送: xwzjyzkx ***@***.***>, Author ***@***.***>主题: Re: [modelscope/modelscope-agent] Bug解答：点击构建按钮报错？ (Issue #255)
本地使用的话，需要你提供oss的配置，因为是使用oss，如果是创空间里面用这个出错，那可能是因为在更新？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/modelscope/modelscope-agent/issues/255#issuecomment-1886439909",
"url": "https://github.com/modelscope/modelscope-agent/issues/255#issuecomment-1886439909",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zzhangpurdue** [comment]
抱歉回复晚了，可以在自己的创空间设置内的环境变量处添加，OSS_ACCESS_KEY_ID， OSS_ACCESS_KEY_SECRET，
OSS_ENDPOINT，OSS_BUCKET_NAME
![image](https://github.com/modelscope/modelscope-agent/assets/5746653/df57896e-b58b-45a9-8bd0-ec8d443a331b)

**Comment by zzhangpurdue** [comment]
长时间未响应，有问题重新开。
