### ISSUE TITLE
error in openai llm: Completions.create() got an unexpected keyword argument 'prompt'

### ISSUE THREAD

**Issue by wenmengzhou** [modelscope/modelscope-agent#300]
error in gradio
![image](https://github.com/modelscope/modelscope-agent/assets/4771825/dea7afc7-0e58-4aeb-b84e-4e6da4847499)

error in backend log
```shell

2024-02-07 16:58:30.882 - modelscope-agent - ERROR -  | message: Traceback (most recent call last):
  File "/home/workspace/modelscope_agent/llm/base.py", line 194, in support_function_calling
    response = self.chat_with_functions(
  File "/home/workspace/modelscope_agent/llm/openai.py", line 115, in chat_with_functions
    response = self.client.completions.create(
  File "/opt/conda/lib/python3.10/site-packages/openai/_utils/_utils.py", line 270, in wrapper
    raise TypeError(msg)
TypeError: Missing required arguments; Expected either ('model' and 'prompt') or ('model', 'prompt' and 'stream') arguments to be given
```

**Comment by wenmengzhou** [comment]
https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/llm/openai.py#L115

problems seems to be here

**Comment by wenmengzhou** [comment]
Error stack trace: 
1. call  support_function_callling https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/llm/openai.py#L58

2. https://github.com/modelscope/modelscope-agent/blob/master/modelscope_agent/llm/base.py#L192
