### ISSUE TITLE
swift包版本不对，导致执行训练demo时报错

### ISSUE THREAD

**Issue by CaC033** [modelscope/modelscope-agent#304]
'''
git clone https://github.com/modelscope/modelscope-agent.git
cd modelscope-agent && pip install -r requirements.txt
'''
以上requirements并没有提供swift包版本。

导致执行以下代码时
'''
cd demo/tool_agent_finetune_swift
PYTHONPATH=./ bash scripts/train/run_qwen_ddp.sh
'''

报错为
'''
Traceback (most recent call last):
  File "/mnt/workspace/modelscope-agent/demo/tool_agent_finetune_swift/llm_sft.py", line 11, in <module>
    from swift.utils import (add_version_to_work_dir, is_master, parse_args,
ImportError: cannot import name 'print_model_info' from 'swift.utils' (/opt/conda/lib/python3.10/site-packages/swift/utils/__init__.py)
'''

**Comment by CaC033** [comment]
能否提供一下能正常运行训练脚本的环境详细版本？

**Comment by CaC033** [comment]
更新swift包版本到1.5.1之后，执行脚本还是会报错

**Comment by CaC033** [comment]
/mnt/workspace/modelscope-agent/demo/tool_agent_finetune_swift> PYTHONPATH=./ bash scripts/train/run_qwen_ddp.sh
Traceback (most recent call last):
  File "/mnt/workspace/modelscope-agent/demo/tool_agent_finetune_swift/llm_sft.py", line 13, in <module>
    from swift.utils.llm_utils import data_collate_fn, print_example, stat_dataset
ModuleNotFoundError: No module named 'swift.utils.llm_utils'
[2024-02-22 17:11:28,701] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14626) of binary: /home/pai/bin/python
Traceback (most recent call last):
  File "/home/pai/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pai/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/pai/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/pai/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by mushenL** [comment]
您好，修复代码已merge,请更新代码再试一次，或者参考https://github.com/modelscope/modelscope-agent/pull/306这个改动修改您的代码试试？
