### ISSUE TITLE
参照demo/demo_register_new_tool.ipynb注册新工具的时候程序报错：NotImplementedError

### ISSUE THREAD

**Issue by fxx-real** [modelscope/modelscope-agent#406]
### Description

你好，我正在测试注册工具功能，并参照demo_register_new_tool.ipynb中的例子，在RenewInstance工具的同文件里写了如下示例工具：
我期望让大模型自主选择一些我提供的本地函数，并由框架执行对应代码，请问是否还需要其他步骤来完成本地新工具的注册？
```
@register_tool('GetData')
class GetDataTool(BaseTool):
    description = 'Get data.'
    name = 'GetData'
    parameters: list = [{
        'name': 'data_type',
        'description': 'Date type you wanted, e.g. person_name',
        'required': True,
        'type': 'string'
    }]

    def call(self, params: str, **kwargs):
        print(kwargs)
        params = self._verify_args(params)
        data_type = params['data_type']
        if data_type == 'person_name':
            return str('张三,李四')
        return str('')
```
调用代码
```
from modelscope_agent.agents import RolePlay
import os

print('请输入DASHSCOPE_API_KEY')
os.environ['DASHSCOPE_API_KEY'] = input()
role_template = '你是一名助手'
llm_config = {
    'model': 'qwen-max',
    'model_server': 'dashscope',
    }
function_list = ['GetData']

bot = RolePlay(function_list=function_list,llm=llm_config, instruction=role_template)

response = bot.run("帮忙取出人名类型数据", remote=False, print_info=True)
text = ''
for chunk in response:
    text += chunk
print(text)
```
报错信息：
```
import GetData failed, details: 'GetData'
....
Traceback (most recent call last):
  File "xxx/modelscope_agent/tools/contrib/demo/test.py", line 24, in <module>
    bot = RolePlay(function_list=function_list,llm=llm_config, instruction=role_template)
  File "xxx/modelscope_agent/agents/role_play.py", line 138, in __init__
    Agent.__init__(self, function_list, llm, storage_path, name,
  File "xxx/modelscope_agent/agent.py", line 49, in __init__
    self._register_tool(function)
  File "xxx/modelscope_agent/agent.py", line 113, in _register_tool
    raise NotImplementedError
NotImplementedError
```

**Comment by fxx-real** [comment]
已解决，没有触发装饰器导致的

**Comment by yanzhang404** [comment]
> 已解决，没有触发装饰器导致的
请问如何解决的

**Comment by chengjixin** [comment]
@yanzhang404 @fxx-real  请问这个问题是如何处理的，我采用master最新代码进行构建

**Comment by yanzhang404** [comment]
> @yanzhang404 @fxx-real 请问这个问题是如何处理的，我采用master最新代码进行构建

我后来发现我自己加的tool只是加了registertool的装饰器，但是其实还要在tool文件夹下的init.py的_import_structure中和base.py的register_map里加上自己定义的工具，加上之后我就可以调用自己的工具了。

**Comment by chengjixin** [comment]
好的，谢谢

**Comment by MrNiebit** [comment]
自己新加tool的话，都要改源码才能让tool注册上吗
